#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Validate the private Beta-3 native TorchNeuron environment for SFT curation.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
NATIVE_VENV="${NATIVE_VENV:-${HOME}/workspace/native_venv}"
HF_HOME="${HF_HOME:-${HOME}/.cache/huggingface}"
INSTALL_DEPS="${INSTALL_DEPS:-0}"

cd "${REPO_ROOT}"
[[ "$(uname -s)" == "Linux" ]] || { echo "ERROR: run this on the Neuron Linux host." >&2; exit 1; }
[[ -f "${NATIVE_VENV}/bin/activate" ]] || {
    echo "ERROR: Beta-3 native venv not found: ${NATIVE_VENV}" >&2
    echo "Create it from the private Beta-3 DLC artifacts described in the user guide." >&2
    exit 1
}
command -v neuron-ls >/dev/null || { echo "ERROR: neuron-ls is unavailable." >&2; exit 1; }

# shellcheck disable=SC1091
source "${NATIVE_VENV}/bin/activate"
export HF_HOME
neuron-ls

if [[ "${INSTALL_DEPS}" == "1" ]]; then
    python -m pip install transformers datasets pandas pyarrow tqdm
fi

python - <<'PY'
import importlib.util

required = ("torch", "transformers", "datasets", "pandas", "pyarrow")
missing = [name for name in required if importlib.util.find_spec(name) is None]
if missing:
    raise SystemExit(
        f"Missing modules: {missing}. Re-run with INSTALL_DEPS=1 after approving dependency installation."
    )
PY
python -m trainium.sft_data_generation_native.check_env
python -m pip check

cat > "${SCRIPT_DIR}/runtime.env" <<EOF
# Generated by setup_env.sh. Re-run after changing the Beta-3 environment.
export NATIVE_VENV="${NATIVE_VENV}"
export TORCHNEURON_IMPORT="${TORCHNEURON_IMPORT:-torch_neuronx}"
export TORCHNEURON_BACKEND="${TORCHNEURON_BACKEND:-neuron}"
export HF_HOME="${HF_HOME}"
export TOKENIZERS_PARALLELISM="false"
export PYTHONUNBUFFERED="1"
EOF

echo "Native environment ready: ${NATIVE_VENV}"
echo "Run the paper-faithful smoke:"
echo "  SMOKE=1 bash trainium/sft_data_generation_native/generate_sft_data.sh"
